#!/bin/bash

# 																				- mayank19o7
#
# .oPYo.   o                 o             o    o                     8                   8
# 8        8                 8             8    8                     8                   8
# `Yooo.  o8P .oPYo. oPYo.  o8P           o8oooo8 o    o .oPYo. oPYo. 8 .oPYo. odYo. .oPYo8
#     `8   8  .oooo8 8  `'   8    ooooo    8    8 8    8 8    8 8  `' 8 .oooo8 8' `8 8    8
#      8   8  8    8 8       8             8    8 8    8 8    8 8     8 8    8 8   8 8    8
# `YooP'   8  `YooP8 8       8             8    8 `YooP8 8YooP' 8     8 `YooP8 8   8 `YooP'
# :.....:::..::.....:..::::::..::::::::::::..:::..:....8 8 ....:..::::..:.....:..::..:.....:
# ::::::::::::::::::::::::::::::::::::::::::::::::::ooP'.8 :::::::::::::::::::::::::::::::::
# ::::::::::::::::::::::::::::::::::::::::::::::::::...::..:::::::::::::::::::::::::::::::::

LOGFILE="$HOME/.local/share/hyprland.log"

# Optionally clear old log
: > "$LOGFILE"

# Start Hyprland and log both stdout and stderr
exec Hyprland >>"$LOGFILE" 2>&1
